### PR TITLE
bpf: add rss feed from fntlnz's blog

### PR DESCRIPTION
**Pull request by fntlnz**
Just adding my blog here. My latest 3 posts are about ebpf and I plan to write more of them.

Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>

### CODE REVIEW

**Comment by fntlnz** [comment]
Any comments on this?

**Comment by tgraf** [comment]
The blogs are awesome, are you using a tag for eBPF that we could filter on? I can see some non-eBPF blogs and we want to limit the feed to coverage on eBPF itself.

**Comment by tgraf** [comment]
Just saw that you are limiting it to the tag, LGTM then

**Comment by fntlnz** [comment]
Thanks @tgraf !

**Pull request merged**
